In [1]:
#Import Thư viện
import numpy as np
import torch
import tensorflow as tf

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe

<h3>Numpy Array và Pytorch/Tensorflow Tensor

Câu 1: Hãy viết chương trình tạo Numpy array, Tensorflow tensor, Pytorch tensor từ danh sách 1
chiều?

In [2]:
list_1D = [i for i in range(1, 10)]

arr_1D = np.array(list_1D)
print('Mảng 1 chiều NumPy:\n', arr_1D, type(arr_1D))

tensor_1D_pt = torch.tensor(list_1D)
print('Tensor PyTorch 1 chiều:\n', tensor_1D_pt, type(tensor_1D_pt))

tensor_1D_tf = tf.convert_to_tensor(list_1D)
print('Tensor Tensorflow 1 chiều:\n', tensor_1D_tf)

Mảng 1 chiều NumPy:
 [1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
Tensor PyTorch 1 chiều:
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) <class 'torch.Tensor'>
Tensor Tensorflow 1 chiều:
 tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)


In [3]:
#Tạo 1 mảng danh sách 2 chiều
list_2D = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]

#Tạo một mảng 2 chiều
arr_2D = np.array(list_2D)

#Kiểm tra hình dạng, kiều dữ liệu và loại
print('Hình dạng của mảng: ', arr_2D.shape)
print('Kiểu dữ liệu của mảng: ', arr_2D.dtype)
print('Loại của mảng: ', type(arr_2D))
print('Mảng: \n', arr_2D)

Hình dạng của mảng:  (3, 3)
Kiểu dữ liệu của mảng:  int32
Loại của mảng:  <class 'numpy.ndarray'>
Mảng: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#Tạo tensor 2 chiều
tensor_2D_pt = torch.tensor(list_2D)

#Kiểm tran hình dạng, kiểu dữ liệu, loại, thiết bị lưu trữ của tensor
print('Hình dạng tensor: ', tensor_2D_pt.shape)
print('Kiểu dữ liệu của tensor: ', tensor_2D_pt.dtype)
print('Loại của tensor: ',type(tensor_2D_pt))
print('Thiết bị lư trữ của tensor: ',tensor_2D_pt.device)
print('Tensor: \n',tensor_2D_pt)

Hình dạng tensor:  torch.Size([3, 3])
Kiểu dữ liệu của tensor:  torch.int64
Loại của tensor:  <class 'torch.Tensor'>
Thiết bị lư trữ của tensor:  cpu
Tensor: 
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [5]:
#Tạo ténor 2 chiều
tensor_2D_tf = tf.convert_to_tensor(arr_2D)

#Kiemr tra hình dạng, kiểu dữ liệu, loại, thiết bị lưu trữ
print('Hình dạng tensor: ', tensor_2D_tf.shape)
print('Kiểu dữ liệu của tensor: ', tensor_2D_tf.dtype)
print('Loại của tensor: ', type(tensor_2D_tf))
print('Thiết bị mà tensor lữu trữ: ',tensor_2D_tf.device)
print('Tensor: \n',tensor_2D_tf)

Hình dạng tensor:  (3, 3)
Kiểu dữ liệu của tensor:  <dtype: 'int32'>
Loại của tensor:  <class 'tensorflow.python.framework.ops.EagerTensor'>
Thiết bị mà tensor lữu trữ:  /job:localhost/replica:0/task:0/device:CPU:0
Tensor: 
 tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


<h3>Các Hàm Khởi Tạo Numpy Array và
Pytorch/Tensorflow Tensor - Phần 1

Chương trình sau tạo array với kích thước (3, 4), đối với thư viện Numpy sử dụng cú pháp np.zeros,
bên trong hàm này chúng ta truyền vào kích thước array chúng ta mong muốn là (3, 4).

In [6]:
#Tạo array toàn số 0
arr_zeros = np.zeros((3,4))
print(arr_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
#Tạo tensor toàn số 0
tensor_zeros = torch.zeros((3, 4))
print(tensor_zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [8]:
#Tạo tensor toàn số 0
tensor_zeros = tf.zeros((3, 4))
print(tensor_zeros)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


Câu 2: ones
Chương trình sau tạo array với kích thước (3, 4), đối với thư viện Numpy sử dụng cú pháp np.ones

In [9]:
arr_ones = np.ones((3,4))
print(arr_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
tensor_ones = torch.ones((3,4))
print(tensor_ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [11]:
tensor_ones = tf.ones((3,4))
print(tensor_ones)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


Câu 3: full, fill
Chương trình sau tạo array với kích thước (3, 4), giá trị hằng số là 5. Đối với thư viện Numpy sử dụng
cú pháp np.full

In [12]:
arr_full = np.full((3, 4), 5)
print(arr_full)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [13]:
tensor_full = torch.full((3,4), 5)
print(tensor_full)

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])


In [14]:
tensor_full = tf.fill([3, 4],5)
print(tensor_full)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


<h3>Các Hàm Khởi Tạo Numpy Array và
Pytorch/Tensorflow Tensor - Phần 2

Câu 1: Hãy viết chương trình tạo Numpy array, Tensorflow tensor, Pytorch tensor trong khoảng [0, 10)
với step=1?

In [15]:
arr_arange = np.arange(1, 10, 1)
print(arr_arange)

[1 2 3 4 5 6 7 8 9]


In [16]:
tensor_arange = torch.arange(1, 10, 1)
print(tensor_arange)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [17]:
tensor_range = tf.range(1, 10, 1)
print(tensor_range)

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)


Câu 2: eye
Trong numpy chúng ta sử dụng hàm np.eye để tạo ma trận đơn vị, trong đó giá trị chúng ta truyền vào
là số lượng hàng của ma trận đầu ra, số lượng cột mặc định bằng số lượng hàng, nếu muốn số lượng
cột khác bạn cần truyền vào hàm eye số lượng cột chỉ định.

In [18]:
arr_eye = np.eye(3)
print(arr_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
tensor_eye = torch.eye(3)
print(tensor_eye)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [20]:
tensor_eye = tf.eye(3)
print(tensor_eye)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


Câu 3: random
Trong Numpy, chúng ta sẽ sử dụng hàm random.rand để tạo mảng với các giá trị ngẫu nhiên trong
khoảng giá trị mặc định là [0, 1). Để tạo mảng với giá trị ngẫu nhiên là số nguyên chúng ta dùng
random.randint, khi sử dụng hàm này ta cần truyền vào khoảng giá trị lấy ngẫu nhiên và kích thước
đầu ra mong muốn.

In [21]:
np.random.seed(2024)

arr_rand = np.random.rand(3, 4)
print('Mảng ngẫu nhiên trong khoảng [0, 1): \n', arr_rand)

arr_randint = np.random.randint(-10, 10, size=(3, 4))
print('Mảng ngãu nhiên trong khoảng [-10, 10): \n',arr_randint)

Mảng ngẫu nhiên trong khoảng [0, 1): 
 [[0.58801452 0.69910875 0.18815196 0.04380856]
 [0.20501895 0.10606287 0.72724014 0.67940052]
 [0.4738457  0.44829582 0.01910695 0.75259834]]
Mảng ngãu nhiên trong khoảng [-10, 10): 
 [[ 5  1 -3  8]
 [-1 -4  0 -9]
 [-5  9 -6 -2]]


In [22]:
torch.manual_seed(2024)

tensor_rand = torch.rand((3, 4))
print('Tensor ngãu nhiên trong khoảng [0, 1): \n', tensor_rand)

tensor_randint = torch.randint(-10, 10, size=(3, 4))
print('Mảng ngãu nhiên trong khoảng [-10, 10): \n', tensor_randint)

Tensor ngãu nhiên trong khoảng [0, 1): 
 tensor([[0.5317, 0.8313, 0.9718, 0.1193],
        [0.1669, 0.3495, 0.2150, 0.6201],
        [0.4849, 0.7492, 0.1521, 0.5625]])
Mảng ngãu nhiên trong khoảng [-10, 10): 
 tensor([[  1,   8,   0,  -2],
        [ -9, -10,  -9,   0],
        [ -3,  -7,  -4,   8]])


In [23]:
tf.random.set_seed(2024)

tensor_rand = tf.random.uniform((3, 4))
print('Tensor ngẫu nhiên trong khoảng [0, 1): \n', tensor_rand)

tensor_randint = tf.random.uniform((3, 4), minval=-10, maxval=10, dtype=tf.int32)
print('Tensor ngẫu nhiên trong khoảng (-10, 10):\n', tensor_randint)

Tensor ngẫu nhiên trong khoảng [0, 1): 
 tf.Tensor(
[[0.90034294 0.19453335 0.36069036 0.66361904]
 [0.76605344 0.2159369  0.6261736  0.07380784]
 [0.22062695 0.934368   0.93327904 0.69267046]], shape=(3, 4), dtype=float32)
Tensor ngẫu nhiên trong khoảng (-10, 10):
 tf.Tensor(
[[-3 -7  9  3]
 [ 2 -5 -3 -5]
 [ 4 -3 -3  5]], shape=(3, 4), dtype=int32)


<h3>Numpy, Pytorch và Tensorflow Hàm Stack và Concatenate

Câu 1: Hãy viết chương trình tạo Numpy 2 array, Pytorch tensor với từ list 1 có giá trị [1, 2, 3], list 2
có giá trị [4, 5, 6]. Sau đó sử dụng hàm hstack để nối theo trục ngang và vstack để nối theo trục dọc?

In [24]:
#Tạo 2 mảng
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4 ,5, 6])

#Nối 2 mảng theo trục ngang
arr_3 = np.hstack((arr_1, arr_2))

print('Mảng 1: \n', arr_1)
print('Mảng 2: \n', arr_2)
print('Mang sau khi nối trục ngang: \n', arr_3)

Mảng 1: 
 [1 2 3]
Mảng 2: 
 [4 5 6]
Mang sau khi nối trục ngang: 
 [1 2 3 4 5 6]


In [25]:
tensor_1 = torch.tensor([1, 2, 3])
tensor_2 = torch.tensor([4, 5, 6])

#Nói 2 tensor theo trục ngang
tensor_3 = torch.hstack((tensor_1, tensor_2))
print('Tensor 1: \n', tensor_1)
print('Tensor2: \n', tensor_2)
print('Tensor sau khi nối trục ngang: \n', tensor_3)

Tensor 1: 
 tensor([1, 2, 3])
Tensor2: 
 tensor([4, 5, 6])
Tensor sau khi nối trục ngang: 
 tensor([1, 2, 3, 4, 5, 6])


Câu 2: vstack
Hàm vstack được sử dụng để nối (hoặc "stack") các array hoặc tensor theo chiều dọc (theo trục hàng).
Trong Numpy, vstack được sử dụng để nối các array theo chiều dọc. Chương trình:

In [26]:
#Tạo 2 mảng
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4 ,5, 6])

#Nối 2 mảng theo trục dọc
arr_3 = np.vstack((arr_1, arr_2))

print('Mảng 1: \n', arr_1)
print('Mảng 2: \n', arr_2)
print('Mang sau khi nối trục dọc: \n', arr_3)

Mảng 1: 
 [1 2 3]
Mảng 2: 
 [4 5 6]
Mang sau khi nối trục dọc: 
 [[1 2 3]
 [4 5 6]]


In [27]:
tensor_1 = torch.tensor([1, 2, 3])
tensor_2 = torch.tensor([4, 5, 6])

#Nói 2 tensor theo trục dọc
tensor_3 = torch.vstack((tensor_1, tensor_2))
print('Tensor 1: \n', tensor_1)
print('Tensor2: \n', tensor_2)
print('Tensor sau khi nối trục dọc: \n', tensor_3)

Tensor 1: 
 tensor([1, 2, 3])
Tensor2: 
 tensor([4, 5, 6])
Tensor sau khi nối trục dọc: 
 tensor([[1, 2, 3],
        [4, 5, 6]])


Câu 3: Concanate
Trong Numpy, concatenate được sử dụng để nối các array theo chiều ngang và dọc. Chương trình:

In [28]:
arr_1 = [[1, 2, 3],
         [4, 5, 6]]
arr_2 = [[7, 8, 9],
         [10, 11, 12]]

arr_3 = np.concatenate((arr_1, arr_2), axis=0)
arr_4 = np.concatenate((arr_1, arr_2), axis=1)

print('Array 1: \n', arr_1)
print('Array 2: \n', arr_2)
print('Nôi theo chiều dọc(axis=0): \n', arr_3)
print('Nối theo chiều ngang(axis=1): \n', arr_4)

Array 1: 
 [[1, 2, 3], [4, 5, 6]]
Array 2: 
 [[7, 8, 9], [10, 11, 12]]
Nôi theo chiều dọc(axis=0): 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Nối theo chiều ngang(axis=1): 
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [29]:
#Pytorch code
tensor_1 = torch.tensor([[1, 2, 3],
                         [4, 5 ,6]])
tensor_2 = torch.tensor([[7, 8, 9],
                         [10, 11, 12]])

#Nối 2 tensor theo chiều dọc axis=0
tensor_3 = torch.cat((tensor_1, tensor_2), dim=0) #torch.concatenate or torch.concat

#Nối 2 tensor theo chiều ngang axis=1
tensor_4 = torch.cat((tensor_1, tensor_2), dim=1)

print('Tensor 1:\n', tensor_1)
print('Tensor 2:\n', tensor_2)
print('Nối theo chiều dọc(axis=0):\n', tensor_3)
print('Nối theo chiều ngang(axis=1):\n', tensor_4)

Tensor 1:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Tensor 2:
 tensor([[ 7,  8,  9],
        [10, 11, 12]])
Nối theo chiều dọc(axis=0):
 tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
Nối theo chiều ngang(axis=1):
 tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])


In [30]:
#Tensorflow code
tensor_1 = tf.convert_to_tensor([[1, 2, 3],
                                 [4, 5, 6]])
tensor_2 = tf.constant([[7, 8, 9],
                        [10, 11, 12]])

#Nối tensor theo chiều dọc axis=0
tensor_3 = tf.concat((tensor_1, tensor_2), axis=0)

#Nối tensor theo chiều dọc axis=1
tensor_4 = tf.concat((tensor_1, tensor_2), axis=1)

print('Tensor 1: \n', tensor_1)
print('Tensor 2: \n', tensor_2)
print('Nối theo chiều dọc(axis=0): \n', tensor_3)
print('Nối theo chiều ngang(axis=1): \n', tensor_4)

Tensor 1: 
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Tensor 2: 
 tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
Nối theo chiều dọc(axis=0): 
 tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)
Nối theo chiều ngang(axis=1): 
 tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


<h3>Các Hàm Quan Trọng Trong Numpy, Pytorch,
Tensorflow - Phần 2

a. Thêm chiều dữ liệu

In [31]:
arr_1 = np.array([1, 2, 3])
#1D -> 2D
arr_2 = arr_1[np.newaxis, :]

#2D -> 5D
arr_3 = arr_2[np.newaxis, :, np.newaxis, :, np.newaxis]

print('array 1: \n',arr_1)
print('array 2: \n', arr_2)
print('array 3: \n', arr_3, arr_3.shape)

array 1: 
 [1 2 3]
array 2: 
 [[1 2 3]]
array 3: 
 [[[[[1]
    [2]
    [3]]]]] (1, 1, 1, 3, 1)


In [32]:
arr_1 = np.array([1, 2, 3])

#1D -> 2D
arr_2 = np.expand_dims(arr_1, axis=0)

#2D -> 5D
arr_3 = np.expand_dims(arr_2, axis=(0, 2, 4))
print('array 1: \n',arr_1, arr_1.shape)
print('array 2: \n', arr_2, arr_2.shape)
print('array 3: \n', arr_3, arr_3.shape)

array 1: 
 [1 2 3] (3,)
array 2: 
 [[1 2 3]] (1, 3)
array 3: 
 [[[[[1]
    [2]
    [3]]]]] (1, 1, 1, 3, 1)


In [33]:
tensor_1 = torch.tensor([1, 2, 3])

#Thêm chiều mới, chuyen từ 1D->2D
tensor_2 = tensor_1[None, :]
#Thêm nhiều chiều mới, chuyển từ 2D->5D
tensor_3 = tensor_2[None, :, None, :, None]

print('Tensor 1:\n', tensor_1, tensor_1.shape)
print('Tensor 2:\n', tensor_2, tensor_2.shape)
print('Tensor 3:\n', tensor_3, tensor_3.shape)


Tensor 1:
 tensor([1, 2, 3]) torch.Size([3])
Tensor 2:
 tensor([[1, 2, 3]]) torch.Size([1, 3])
Tensor 3:
 tensor([[[[[1],
           [2],
           [3]]]]]) torch.Size([1, 1, 1, 3, 1])


In [34]:
#Tensorflow code
tensor_1 = tf.constant([1, 2, 3,])

#1D -> 2D
tensor_2 = tensor_1[None, :]

#2D -> 5D:
tensor_3 = tensor_2[None, :, None, :, None]

print('Tensor 1:\n', tensor_1, tensor_1.shape)
print('Tensor 2:\n', tensor_2, tensor_2.shape)
print('Tensor 3:\n', tensor_3, tensor_3.shape)

Tensor 1:
 tf.Tensor([1 2 3], shape=(3,), dtype=int32) (3,)
Tensor 2:
 tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32) (1, 3)
Tensor 3:
 tf.Tensor(
[[[[[1]
    [2]
    [3]]]]], shape=(1, 1, 1, 3, 1), dtype=int32) (1, 1, 1, 3, 1)


b. Reshape


In [35]:
arr_2D = np.array([[1, 2, 3],
                   [4, 5, 6]])

arr_1D = np.reshape(arr_2D, newshape=(6, )) #arr_1D = arr_2D.reshape(6,)

print('array 2D:\n', arr_2D)
print('array 1D:\n', arr_1D)

array 2D:
 [[1 2 3]
 [4 5 6]]
array 1D:
 [1 2 3 4 5 6]


Câu 1: Viết chương trình tạo một Numpy array, Pytorch tensor, Tensorflow tensor từ list 1D có giá
trị [2, 3, 5, 7]. Sau đó thực hiện thêm một chiều mới ở vị trí 0 để tạo array, tensor 2D. Sau đó tiếp tục
thêm các chiều mới ở vị trí 1, 3 và 4 để tạo array, tensor 5D.

In [36]:
#Numpy code
arr_1D = np.array([2, 3, 5, 7])

#1D -> 2D
arr_2D = arr_1D[np.newaxis, :]

#2D -> 5D
arr_5D = np.expand_dims(arr_2D, axis=(1, 3, 4))

print('array 1D:\n', arr_1D, arr_1D.shape)
print('array 2D: \n', arr_2D, arr_2D.shape)
print('array 5D:\n', arr_5D, arr_5D.shape)

array 1D:
 [2 3 5 7] (4,)
array 2D: 
 [[2 3 5 7]] (1, 4)
array 5D:
 [[[[[2]]

   [[3]]

   [[5]]

   [[7]]]]] (1, 1, 4, 1, 1)


In [37]:
#Pytorch code
tensor_1D = torch.tensor([2, 3, 5, 7])

#1D -> 2D
tensor_2D = tensor_1D[None, :]

#2D -> 5D
tensor_5D = tensor_2D[:, None, :, None, None]

print('Tensor 1D:\n', tensor_1D, tensor_1D.shape)
print('Tensor 2D:\n', tensor_2D, tensor_2D.shape)
print('Tensor 5D:\n', tensor_5D, tensor_5D.shape)

Tensor 1D:
 tensor([2, 3, 5, 7]) torch.Size([4])
Tensor 2D:
 tensor([[2, 3, 5, 7]]) torch.Size([1, 4])
Tensor 5D:
 tensor([[[[[2]],

          [[3]],

          [[5]],

          [[7]]]]]) torch.Size([1, 1, 4, 1, 1])


In [38]:
#Pytorch code
tensor_1D = tf.convert_to_tensor([2, 3, 5, 7])

#1D -> 2D
tensor_2D = tensor_1D[None, :]

#2D -> 5D
tensor_5D = tensor_2D[:, None, :, None, None]

print('Tensor 1D:\n', tensor_1D, tensor_1D.shape)
print('Tensor 2D:\n', tensor_2D, tensor_2D.shape)
print('Tensor 5D:\n', tensor_5D, tensor_5D.shape)

Tensor 1D:
 tf.Tensor([2 3 5 7], shape=(4,), dtype=int32) (4,)
Tensor 2D:
 tf.Tensor([[2 3 5 7]], shape=(1, 4), dtype=int32) (1, 4)
Tensor 5D:
 tf.Tensor(
[[[[[2]]

   [[3]]

   [[5]]

   [[7]]]]], shape=(1, 1, 4, 1, 1), dtype=int32) (1, 1, 4, 1, 1)


<h3>Các Hàm Quan Trọng Trong Numpy, Pytorch,
Tensorflow - Phần 3

In [39]:
np.random.seed(2024)

arr_rand = np.random.randint(-10, 10, size=(3, 3))

print('Mảng ngẫu nhiên: \n', arr_rand)

arr_clip = np.clip(arr_rand, a_min=3, a_max=8)
print('mảng sau khi được cắt trong khoảng {3, 8}\n', arr_clip)

Mảng ngẫu nhiên: 
 [[ -2 -10 -10]
 [ -6  -1  -9]
 [ -7   0  -8]]
mảng sau khi được cắt trong khoảng {3, 8}
 [[3 3 3]
 [3 3 3]
 [3 3 3]]


In [40]:
torch.manual_seed(2024)

tensor_rand = torch.randint(-10, 10, size=(3, 4))
print('Tensor ngẫu nhiên: \n', tensor_rand)

tensor_clip = torch.clamp(tensor_rand, min=3, max=8) # or torch.clip()
print('Tensor clip: \n', tensor_clip)


Tensor ngẫu nhiên: 
 tensor([[  2,   0,  -6, -10],
        [ -7, -10,   0,   1],
        [  3,   9,   7,  -6]])
Tensor clip: 
 tensor([[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 8, 7, 3]])


In [41]:
tf.random.set_seed(2024)

tensor_rand = tf.random.uniform((3, 4), minval=-10, maxval=10, dtype=tf.int32)
print('Tensor ngẫu nhiên: \n', tensor_rand)

tensor_clip = tf.clip_by_value(tensor_rand, clip_value_min=3, clip_value_max=8)
print('Tensor clip: \n', tensor_clip)

Tensor ngẫu nhiên: 
 tf.Tensor(
[[-6 -2  0 -2]
 [ 4  4 -9  3]
 [ 7  1  2 -5]], shape=(3, 4), dtype=int32)
Tensor clip: 
 tf.Tensor(
[[3 3 3 3]
 [4 4 3 3]
 [7 3 3 3]], shape=(3, 4), dtype=int32)


Câu 1: Viết chương trình tạo một Numpy array, Pytorch tensor, Tensorflow tensor với các giá trị số
nguyên ngẫu nhiên trong khoảng [-5, 10) với kích thước (4, 3). Sử dụng hàm clip để cắt các giá trị nằm
ngoài khoảng [-2, 0]? Lưu ý: Sử dụng seed=2024

In [42]:
#Numpy code
np.random.seed(2024)

arr_rand = np.random.randint(-5, 10, size=(4, 3))

print('Mảng ngẫu nhiên: \n', arr_rand)

arr_clip = np.clip(arr_rand, a_min=-2, a_max=0)
print('mảng sau khi được cắt trong khoảng {3, 8}\n', arr_clip)

Mảng ngẫu nhiên: 
 [[ 3  5 -5]
 [-5  6 -1]
 [ 9  2  4]
 [-4  7 -2]]
mảng sau khi được cắt trong khoảng {3, 8}
 [[ 0  0 -2]
 [-2  0 -1]
 [ 0  0  0]
 [-2  0 -2]]


In [43]:
#Pytorch code
torch.manual_seed(2024)

tensor_rand = torch.randint(-5, 10, size=(4, 3))
print('Tensor ngẫu nhiên: \n', tensor_rand)

tensor_clip = torch.clip(tensor_rand, min=-2, max=0)
print('Tensor clip: \n', tensor_clip)

Tensor ngẫu nhiên: 
 tensor([[-3,  0, -1],
        [ 0, -2,  0],
        [ 5,  6,  3],
        [ 4, -3, -1]])
Tensor clip: 
 tensor([[-2,  0, -1],
        [ 0, -2,  0],
        [ 0,  0,  0],
        [ 0, -2, -1]])


In [44]:
#Pytorch code
tf.random.set_seed(2024)

tensor_rand = tf.random.uniform((4, 3), minval=-5, maxval=10, dtype=tf.int32)
print('Tensor ngẫu nhiên: \n', tensor_rand)

tensor_clip = tf.clip_by_value(tensor_rand, clip_value_min=-2, clip_value_max=0)
print('Tensor clip: \n', tensor_clip)

Tensor ngẫu nhiên: 
 tf.Tensor(
[[ 4  3  0]
 [ 3  9  9]
 [-4 -2  2]
 [ 6  2  0]], shape=(4, 3), dtype=int32)
Tensor clip: 
 tf.Tensor(
[[ 0  0  0]
 [ 0  0  0]
 [-2 -2  0]
 [ 0  0  0]], shape=(4, 3), dtype=int32)


<h3>Indexing Trong Numpy, Pytorch và Tensorflow -
Phần 1

<b>Bài tập</b>
Hãy viết chương trình để tạo một numpy array, PyTorch tensor và TensorFlow tensor từ một list 3D
có giá trị như sau: [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]]. Sau đó sử dụng
slicing thực hiện các yêu cầu sau:<br>
- Sử dụng slicing để lấy một phần của array, tensor tại vị trí index (0, 1) của mảng 2D trong mảng
3D và giữ nguyên số chiều

In [45]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
arr.shape

(3, 2, 3)

In [46]:
#Giữ nguyên số chiều
arr[0:1, 0:1, 1:2]

array([[[2]]])

- Sử dụng slicing để lấy một phần của array, tensor tại vị trí index (0, 1) của mảng 2D trong mảng
3D, nhưng giảm đi một chiều.

In [47]:
#Giảm đi 1 chiều
arr[0, 0:1, 1:2]

array([[2]])

<h3>Indexing Trong Numpy, Pytorch và Tensorflow -
Phần 2

Câu 1: Cho một list 2D như sau:<br>
[[1 , 0, 1],<br>
[0, 1, 0],<br>
[1, 0, 1]]<br>
Hãy tạo array, tensor( Pytorch, Tensorflow) từ list 2D này sau đó thực hiện các yêu cầu sau:<br>
- Lấy hàng thứ 2(index=1) theo 2 cách giữ nguyên hoặc giảm số chiều<br>
- Lấy cột thứ nhất(index=0) theo 2 cách giữ nguyên hoặc giảm số chiều

In [50]:
#Code Numpy
arr = np.array([[1 , 0, 1],
                [0, 1, 0],
                [1, 0, 1]])

#Lấy hàng 2 giữa nguyên số chiều
print('Hàng 2 giữ nguyên số chiều: \n', arr[1:2, :])

#Lấy hàng 2 giảm số chiều
print('Hàng 2 giảm số chiều: \n', arr[1, :])

#Lấy cột 1 giữa nguyên số chiều
print('Cột 1 giữa nguyên số chiều: \n', arr[:, 0:1])

#Lấy cột 1 giảm số chiều
print('Cột 1 giảm số chiều: \n', arr[:, 0])

Hàng 2 giữ nguyên số chiều: 
 [[0 1 0]]
Hàng 2 giảm số chiều: 
 [0 1 0]
Cột 1 giữa nguyên số chiều: 
 [[1]
 [0]
 [1]]
Cột 1 giảm số chiều: 
 [1 0 1]


In [51]:
#Code pytorch
tensor = torch.tensor([[1 , 0, 1],
                        [0, 1, 0],
                        [1, 0, 1]])

#Lấy hàng 2 giữa nguyên số chiều
print('Hàng 2 giữ nguyên số chiều: \n', tensor[1:2, :])

#Lấy hàng 2 giảm số chiều
print('Hàng 2 giảm số chiều: \n', tensor[1, :])

#Lấy cột 1 giữa nguyên số chiều
print('Cột 1 giữa nguyên số chiều: \n', tensor[:, 0:1])

#Lấy cột 1 giảm số chiều
print('Cột 1 giảm số chiều: \n', tensor[:, 0])

Hàng 2 giữ nguyên số chiều: 
 tensor([[0, 1, 0]])
Hàng 2 giảm số chiều: 
 tensor([0, 1, 0])
Cột 1 giữa nguyên số chiều: 
 tensor([[1],
        [0],
        [1]])
Cột 1 giảm số chiều: 
 tensor([1, 0, 1])


In [52]:
#Code tensorflow
tensor = tf.constant([[1 , 0, 1],
                        [0, 1, 0],
                        [1, 0, 1]])

#Lấy hàng 2 giữa nguyên số chiều
print('Hàng 2 giữ nguyên số chiều: \n', tensor[1:2, :])

#Lấy hàng 2 giảm số chiều
print('Hàng 2 giảm số chiều: \n', tensor[1, :])

#Lấy cột 1 giữa nguyên số chiều
print('Cột 1 giữa nguyên số chiều: \n', tensor[:, 0:1])

#Lấy cột 1 giảm số chiều
print('Cột 1 giảm số chiều: \n', tensor[:, 0])

Hàng 2 giữ nguyên số chiều: 
 tf.Tensor([[0 1 0]], shape=(1, 3), dtype=int32)
Hàng 2 giảm số chiều: 
 tf.Tensor([0 1 0], shape=(3,), dtype=int32)
Cột 1 giữa nguyên số chiều: 
 tf.Tensor(
[[1]
 [0]
 [1]], shape=(3, 1), dtype=int32)
Cột 1 giảm số chiều: 
 tf.Tensor([1 0 1], shape=(3,), dtype=int32)


Câu 2: Viết chương trình tạo một Numpy array, Pytorch tensor, Tensorflow tensor với các giá trị số
nguyên ngẫu nhiên trong khoảng [-10, 10) với kích thước (3, 3). Sau đó sử dụng Boolean indices để lọc
các phần tử lớn hơn 0. Lưu ý: sử dụng seed=2024

In [59]:
#Code Numpy
np.random.seed(2024)

arr_rand = np.random.randint(-10, 10, size=(3, 3))
print('Mảng ngãu nhiên: \n', arr_rand)

bool_check = arr_rand>0
print('Mảng sau khi kiểm tra ddieuf kiện: ', arr_rand[bool_check])

Mảng ngãu nhiên: 
 [[ -2 -10 -10]
 [ -6  -1  -9]
 [ -7   0  -8]]
Mảng sau khi kiểm tra ddieuf kiện:  []


In [61]:
#Code Pytorch
torch.manual_seed(2024)

tensor_rand = torch.randint(-10, 10, size=(3, 3))
print('Tensor ngẫu nhiên: \n', tensor_rand)

bool_check = tensor_rand>0
print('Tensor sau khi kiểm tra điều kiện: \n', tensor_rand[bool_check])

Tensor ngẫu nhiên: 
 tensor([[  2,   0,  -6],
        [-10,  -7, -10],
        [  0,   1,   3]])
Tensor sau khi kiểm tra điều kiện: 
 tensor([2, 1, 3])


In [62]:
#Code Tensorflow
tf.random.set_seed(2024)

tensor_rand = tf.random.uniform(shape=(3, 3), minval=-10, maxval=10, dtype=tf.int32)
print('Tensor ngẫu nhiên: \n', tensor_rand)

bool_check = tensor_rand>0
print('Tensor sau khi kiểm tra điều kiện: \n', tensor_rand[bool_check])

Tensor ngẫu nhiên: 
 tf.Tensor(
[[-6 -2  0]
 [-2  4  4]
 [-9  3  7]], shape=(3, 3), dtype=int32)
Tensor sau khi kiểm tra điều kiện: 
 tf.Tensor([4 4 3 7], shape=(4,), dtype=int32)


<h3>Các Phép Tính Numpy, Pytorch và Tensorflow -
Phần 1

Cho hai list 2D như sau:

In [64]:
lst_1 = [[1 , -2, 1],
        [-3, 1, 0],
        [-2, 5, 1]]

lst_2 = [[1 , 3, 5],
        [2, 4, 6],
        [3, 5, 7]]

Hãy tạo 2 array, tensor( Pytorch, Tensorflow) từ list 2D này sau đó thực hiện các phép tính addition
và subtraction giữa hai array, tensor vừa tạo.

In [66]:
#code Numpy
arr_1 = np.array(lst_1)
arr_2 = np.array(lst_2)

arr_3 = arr_1 + arr_2

arr_4 = arr_1 - arr_2

print('Mảng 1: \n', arr_1)
print("Mảng 2: \n", arr_2)
print('Tổng 2 mảng: \n', arr_3)
print('Hiệu 2 mảng:\n', arr_4)

Mảng 1: 
 [[ 1 -2  1]
 [-3  1  0]
 [-2  5  1]]
Mảng 2: 
 [[1 3 5]
 [2 4 6]
 [3 5 7]]
Tổng 2 mảng: 
 [[ 2  1  6]
 [-1  5  6]
 [ 1 10  8]]
Hiệu 2 mảng:
 [[ 0 -5 -4]
 [-5 -3 -6]
 [-5  0 -6]]


In [67]:
#Code Pytorch
tensor_1 = torch.tensor(lst_1)
tensor_2 = torch.tensor(lst_2)

tensor_3 = tensor_1 + tensor_2

tensor_4 = tensor_1 - tensor_2

print('Tensor 1: \n', tensor_1)
print("Tensor 2: \n", tensor_2)
print('Tổng 2 tensor: \n', tensor_3)
print('Hiệu 2 tensor:\n', tensor_4)

Tensor 1: 
 tensor([[ 1, -2,  1],
        [-3,  1,  0],
        [-2,  5,  1]])
Tensor 2: 
 tensor([[1, 3, 5],
        [2, 4, 6],
        [3, 5, 7]])
Tổng 2 tensor: 
 tensor([[ 2,  1,  6],
        [-1,  5,  6],
        [ 1, 10,  8]])
Hiệu 2 tensor:
 tensor([[ 0, -5, -4],
        [-5, -3, -6],
        [-5,  0, -6]])


In [68]:
#Code tensorflow
tensor_1 = tf.constant(lst_1)
tensor_2 = tf.convert_to_tensor(lst_2)

tensor_3 = tensor_1 + tensor_2

tensor_4 = tensor_1 - tensor_2

print('Tensor 1: \n', tensor_1)
print("Tensor 2: \n", tensor_2)
print('Tổng 2 tensor: \n', tensor_3)
print('Hiệu 2 tensor:\n', tensor_4)

Tensor 1: 
 tf.Tensor(
[[ 1 -2  1]
 [-3  1  0]
 [-2  5  1]], shape=(3, 3), dtype=int32)
Tensor 2: 
 tf.Tensor(
[[1 3 5]
 [2 4 6]
 [3 5 7]], shape=(3, 3), dtype=int32)
Tổng 2 tensor: 
 tf.Tensor(
[[ 2  1  6]
 [-1  5  6]
 [ 1 10  8]], shape=(3, 3), dtype=int32)
Hiệu 2 tensor:
 tf.Tensor(
[[ 0 -5 -4]
 [-5 -3 -6]
 [-5  0 -6]], shape=(3, 3), dtype=int32)


<h3>Các Phép Tính Numpy, Pytorch và Tensorflow -
Phần 2

Cho hai list 2D như sau:

In [69]:
lst_1 = [[1 , -2, 1],
        [-3, 1, 4],
        [-2, 5, 1]]

lst_2 = [[1 , 3, 5],
        [2, 4, 6],
        [3, 5, 7]]

Hãy tạo 2 array, tensor( Pytorch, Tensorflow) từ list 2D này sau đó thực hiện các phép tính multiplication
và division giữa hai array, tensor vừa tạo.

In [70]:
#code Numpy
arr_1 = np.array(lst_1)
arr_2 = np.array(lst_2)

arr_3 = arr_1 * arr_2

arr_4 = arr_1 / arr_2

print('Mảng 1: \n', arr_1)
print("Mảng 2: \n", arr_2)
print('Tích element-wise 2 mảng: \n', arr_3)
print('Thương 2 mảng:\n', arr_4)

Mảng 1: 
 [[ 1 -2  1]
 [-3  1  4]
 [-2  5  1]]
Mảng 2: 
 [[1 3 5]
 [2 4 6]
 [3 5 7]]
Tích element-wise 2 mảng: 
 [[ 1 -6  5]
 [-6  4 24]
 [-6 25  7]]
Thương 2 mảng:
 [[ 1.         -0.66666667  0.2       ]
 [-1.5         0.25        0.66666667]
 [-0.66666667  1.          0.14285714]]


In [71]:
#Code Pytorch
tensor_1 = torch.tensor(lst_1)
tensor_2 = torch.tensor(lst_2)

tensor_3 = tensor_1 * tensor_2

tensor_4 = tensor_1 / tensor_2

print('Tensor 1: \n', tensor_1)
print("Tensor 2: \n", tensor_2)
print('Tích element-wise tensor: \n', tensor_3)
print('Thươnng 2 tensor:\n', tensor_4)

Tensor 1: 
 tensor([[ 1, -2,  1],
        [-3,  1,  4],
        [-2,  5,  1]])
Tensor 2: 
 tensor([[1, 3, 5],
        [2, 4, 6],
        [3, 5, 7]])
Tích element-wise tensor: 
 tensor([[ 1, -6,  5],
        [-6,  4, 24],
        [-6, 25,  7]])
Thươnng 2 tensor:
 tensor([[ 1.0000, -0.6667,  0.2000],
        [-1.5000,  0.2500,  0.6667],
        [-0.6667,  1.0000,  0.1429]])


In [72]:
#Code tensorflow
tensor_1 = tf.constant(lst_1)
tensor_2 = tf.convert_to_tensor(lst_2)

tensor_3 = tensor_1 * tensor_2

tensor_4 = tensor_1 / tensor_2

print('Tensor 1: \n', tensor_1)
print("Tensor 2: \n", tensor_2)
print('Tích element-wise 2 tensor: \n', tensor_3)
print('Thươnng 2 tensor:\n', tensor_4)

Tensor 1: 
 tf.Tensor(
[[ 1 -2  1]
 [-3  1  4]
 [-2  5  1]], shape=(3, 3), dtype=int32)
Tensor 2: 
 tf.Tensor(
[[1 3 5]
 [2 4 6]
 [3 5 7]], shape=(3, 3), dtype=int32)
Tích element-wise 2 tensor: 
 tf.Tensor(
[[ 1 -6  5]
 [-6  4 24]
 [-6 25  7]], shape=(3, 3), dtype=int32)
Thươnng 2 tensor:
 tf.Tensor(
[[ 1.         -0.66666667  0.2       ]
 [-1.5         0.25        0.66666667]
 [-0.66666667  1.          0.14285714]], shape=(3, 3), dtype=float64)


<h3>Các Phép Tính Numpy, Pytorch và Tensorflow -
Phần 3

Câu 1: Cho hai vector a = [1, 4, 7], b = [9, 2, 3] Tính tích vô hướng của hai vector này bằng ba thư
viện Numpy, Pytorch vầ Tensorfow

In [73]:
#Code numpy
a = np.array([1, 4, 7])
b = np.array([9, 2, 3])

c = np.dot(a, b)

print('vector a: \n', a)
print("vector b: \n", b)
print('Tích vô hướng 2 vector: \n', c)


vector a: 
 [1 4 7]
vector b: 
 [9 2 3]
Tích vô hướng 2 vector: 
 38


In [74]:
#Code pytorch
a = torch.tensor([1, 4, 7])
b = torch.tensor([9, 2, 3])

c = torch.dot(a, b)

print('vector a: \n', a)
print("vector b: \n", b)
print('Tích vô hướng 2 vector: \n', c)

vector a: 
 tensor([1, 4, 7])
vector b: 
 tensor([9, 2, 3])
Tích vô hướng 2 vector: 
 tensor(38)


In [79]:
#Code tensorflow
a = tf.constant([1, 4, 7])
b = tf.convert_to_tensor([9, 2, 3])

c = tf.tensordot(a, b, axes=1) #axes=0 lấy từng element a nhân với vector b shape kq=3x3

print('vector a: \n', a)
print("vector b: \n", b)
print('Tích vô hướng 2 vector: \n', c)

vector a: 
 tf.Tensor([1 4 7], shape=(3,), dtype=int32)
vector b: 
 tf.Tensor([9 2 3], shape=(3,), dtype=int32)
Tích vô hướng 2 vector: 
 tf.Tensor(38, shape=(), dtype=int32)


Câu 2: Viết chương trình tạo hai Numpy array, Pytorch tensor, Tensorflow tensor với các giá trị số
nguyên ngẫu nhiên trong khoảng [-10, 10) với kích thước (3, 3). Hãy tính matrix multiplication hai ma
trận này bằng ba thư viện Numpy, Pytorch và Tensorflow. Lưu ý: sử dụng seed=2024

In [84]:
#Code Numpy
np.random.seed(2024)
arr_rand_1 = np.random.randint(-10, 10, (3,3))
arr_rand_2 = np.random.randint(-10, 10, (3,3))

arr = np.matmul(arr_rand_1, arr_rand_2)

print('matrix 1: \n', arr_rand_1)
print("matrix 2: \n", arr_rand_2)
print('Matrix multiplication : \n', arr)

matrix 1: 
 [[ -2 -10 -10]
 [ -6  -1  -9]
 [ -7   0  -8]]
matrix 2: 
 [[-10  -5   7]
 [  5   0   4]
 [  5   1  -3]]
Matrix multiplication : 
 [[-80   0 -24]
 [ 10  21 -19]
 [ 30  27 -25]]


In [86]:
#Code pytorch
torch.manual_seed(2024)
tensor_rand_1 = torch.randint(-10, 10, (3,3))
tensor_rand_2 = torch.randint(-10, 10, (3,3))

tensor = torch.matmul(tensor_rand_1, tensor_rand_2)

print('matrix 1: \n', tensor_rand_1)
print("matrix 2: \n", tensor_rand_2)
print('Matrix multiplication: \n', tensor)

matrix 1: 
 tensor([[  2,   0,  -6],
        [-10,  -7, -10],
        [  0,   1,   3]])
matrix 2: 
 tensor([[  9,   7,  -6],
        [  1,   8,   0],
        [ -2,  -9, -10]])
Matrix multiplication: 
 tensor([[ 30,  68,  48],
        [-77, -36, 160],
        [ -5, -19, -30]])


In [89]:
#Code tensorflow
tf.random.set_seed(2024)
tensor_rand_1 = tf.random.uniform((3,3), minval=-10, maxval=10, dtype=tf.int32)
tensor_rand_2 = tf.random.uniform((3,3), minval=-10, maxval=10, dtype=tf.int32)

tensor = tf.matmul(tensor_rand_1, tensor_rand_2)

print('matrix 1: \n', tensor_rand_1)
print("matrix 2: \n", tensor_rand_2)
print('Matrix multiplication: \n', tensor)

matrix 1: 
 tf.Tensor(
[[-6 -2  0]
 [-2  4  4]
 [-9  3  7]], shape=(3, 3), dtype=int32)
matrix 2: 
 tf.Tensor(
[[-3 -7  9]
 [ 3  2 -5]
 [-3 -5  4]], shape=(3, 3), dtype=int32)
Matrix multiplication: 
 tf.Tensor(
[[ 12  38 -44]
 [  6   2 -22]
 [ 15  34 -68]], shape=(3, 3), dtype=int32)


<h3>Các Phép Tính Numpy, Pytorch và Tensorflow
Transpose và Summation

Câu 1: Viết chương trình tạo hai Numpy array, Pytorch tensor, Tensorflow tensor với các giá trị số
nguyên ngẫu nhiên trong khoảng [-10, 10) với kích thước (3, 4). Sau đó chuyển vị array, tensor thứ 2
và thực hiện phép nhân matrix multiplication. Lưu ý: sử dụng seed=2024

In [91]:
#Code Numpy
np.random.seed(2024)
arr_rand = np.random.randint(-10, 10, (3,4))
arr_transpose = np.transpose(arr_rand)

arr = np.matmul(arr_rand, arr_transpose)

print('matrix : \n', arr_rand)
print("matrix transpose: \n", arr_transpose)
print('Matrix multiplication : \n', arr)

matrix : 
 [[ -2 -10 -10  -6]
 [ -1  -9  -7   0]
 [ -8 -10  -5   7]]
matrix transpose: 
 [[ -2  -1  -8]
 [-10  -9 -10]
 [-10  -7  -5]
 [ -6   0   7]]
Matrix multiplication : 
 [[240 162 124]
 [162 131 133]
 [124 133 238]]


In [94]:
#Code pytorch
torch.manual_seed(2024)
tensor_rand = torch.randint(-10, 10, (3,4))
tensor_transpose = torch.t(tensor_rand)
# tensor_transpose = torch.transpose(tensor_rand, 0, 1)

tensor = torch.matmul(tensor_rand, tensor_transpose)

print('matrix : \n', tensor_rand)
print("matrix transpose: \n", tensor_transpose)
print('Matrix multiplication: \n', tensor)

matrix 1: 
 tensor([[  2,   0,  -6, -10],
        [ -7, -10,   0,   1],
        [  3,   9,   7,  -6]])
matrix 2: 
 tensor([[  2,  -7,   3],
        [  0, -10,   9],
        [ -6,   0,   7],
        [-10,   1,  -6]])
Matrix multiplication: 
 tensor([[ 140,  -24,   24],
        [ -24,  150, -117],
        [  24, -117,  175]])


In [95]:
#Code tensorflow
tf.random.set_seed(2024)
tensor_rand = tf.random.uniform((3,4), minval=-10, maxval=10, dtype=tf.int32)
tensor_transpose = tf.transpose(tensor_rand)

tensor = tf.matmul(tensor_rand, tensor_transpose)

print('matrix : \n', tensor_rand)
print("matrix transpose: \n", tensor_transpose)
print('Matrix multiplication: \n', tensor)

matrix : 
 tf.Tensor(
[[-6 -2  0 -2]
 [ 4  4 -9  3]
 [ 7  1  2 -5]], shape=(3, 4), dtype=int32)
matrix transpose: 
 tf.Tensor(
[[-6  4  7]
 [-2  4  1]
 [ 0 -9  2]
 [-2  3 -5]], shape=(4, 3), dtype=int32)
Matrix multiplication: 
 tf.Tensor(
[[ 44 -38 -34]
 [-38 122  -1]
 [-34  -1  79]], shape=(3, 3), dtype=int32)


Câu 2: Viết chương trình tạo một Numpy array, Pytorch tensor, Tensorflow tensor với các giá trị số
nguyên ngẫu nhiên trong khoảng [-10, 10) với kích thước (3, 3). Sau đó hãy tính tổng của toàn bộ
tensor, array, tiếp theo tính tổng theo chiều dọc, chiều ngang . Lưu ý: sử dụng seed=2024

In [96]:
#Code Numpy
np.random.seed(2024)
arr_rand = np.random.randint(-10, 10, (3,3))

print('matrix : \n', arr_rand)
print("Tổng toàn bộ: \n", np.sum(arr_rand))
print('Tổng theo chiều dọc : \n', np.sum(arr_rand, axis=0))
print('Tổng theo chiều ngang : \n', np.sum(arr_rand, axis=1))

matrix : 
 [[ -2 -10 -10]
 [ -6  -1  -9]
 [ -7   0  -8]]
Tổng toàn bộ: 
 -53
Tổng theo chiều dọc : 
 [-15 -11 -27]
Tổng theo chiều ngang : 
 [-22 -16 -15]


In [97]:
#Code pytorch
torch.manual_seed(2024)
tensor_rand = torch.randint(-10, 10, (3,3))

print('matrix : \n', tensor_rand)
print("Tổng toàn bộ: \n", torch.sum(tensor_rand))
print('Tổng theo chiều dọc : \n', torch.sum(tensor_rand, axis=0))
print('Tổng theo chiều ngang : \n', torch.sum(tensor_rand, axis=1))

matrix : 
 tensor([[  2,   0,  -6],
        [-10,  -7, -10],
        [  0,   1,   3]])
Tổng toàn bộ: 
 tensor(-27)
Tổng theo chiều dọc : 
 tensor([ -8,  -6, -13])
Tổng theo chiều ngang : 
 tensor([ -4, -27,   4])


In [99]:
#Code tensorfow
tf.random.set_seed(2024)
tensor_rand = tf.random.uniform((3,3), minval=-10, maxval=10, dtype=tf.int32)

print('matrix : \n', tensor_rand)
print("Tổng toàn bộ: \n", tf.reduce_sum(tensor_rand))
print('Tổng theo chiều dọc : \n', tf.reduce_sum(tensor_rand, axis=0))
print('Tổng theo chiều ngang : \n', tf.reduce_sum(tensor_rand, axis=1))

matrix : 
 tf.Tensor(
[[-6 -2  0]
 [-2  4  4]
 [-9  3  7]], shape=(3, 3), dtype=int32)
Tổng toàn bộ: 
 tf.Tensor(-1, shape=(), dtype=int32)
Tổng theo chiều dọc : 
 tf.Tensor([-17   5  11], shape=(3,), dtype=int32)
Tổng theo chiều ngang : 
 tf.Tensor([-8  6  1], shape=(3,), dtype=int32)
