Các phép tính Numpy, Pytorch và tensorflow Transpose và summation<br>


In [ ]:
import numpy as np
import torch
import tensorflow as tf

Transposed with numpy

In [3]:
arr_1 = np.array([[1, 2], [3, 4]])
print(f'Array: \n {arr_1}')

arr_transposed_1 = np.transpose(arr_1)
print(f'Transposed method 1:\n {arr_transposed_1}')

arr_transposed_2 = arr_1.T
print(f'Transposed method 2: \n {arr_transposed_2}')

Array: 
 [[1 2]
 [3 4]]
Transposed method 1:
 [[1 3]
 [2 4]]
Transposed method 2: 
 [[1 3]
 [2 4]]


Transposed with pytorch


In [5]:
tensor_pt = torch.tensor([[1, 2], [3, 4]])
print(f'Tensor with pytorch: \n {tensor_pt}')

transposed_tensor_pt_1 = torch.transpose(tensor_pt,0, 1)
print(f'Transposed with pytorch 1: \n {transposed_tensor_pt_1}')

transposed_tensor_pt_2 = torch.t(tensor_pt)
print(f'Transposed with pytorch 2: \n{transposed_tensor_pt_2}')

Tensor with pytorch: 
 tensor([[1, 2],
        [3, 4]])
Transposed with pytorch 1: 
 tensor([[1, 3],
        [2, 4]])
Tensor with pytorch transposed: 
tensor([[1, 3],
        [2, 4]])


Transposed with tensorflow

In [8]:
tensor_tf = tf.constant([[1, 2], [3, 4]])
print(f'Tensor with tensorflow:\n {tensor_tf}')

transposed_tensor_tf = tf.transpose(tensor_tf)
print(f'Tensor with tensorflow transposed: \n{transposed_tensor_tf}')

Tensor with tensorflow:
 [[1 2]
 [3 4]]
Tensor with tensorflow transposed: 
[[1 3]
 [2 4]]


b. Summation

In [9]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
total_arr = np.sum(arr)
column_sum = np.sum(arr, axis=0)
row_sum = np.sum(arr, axis=1)

print(arr)
print(f'sum array: \n {total_arr}')
print(f'sum column arr: \n {column_sum}')
print(f'sum row arrar: \n {row_sum}')

[[1 2 3]
 [4 5 6]]
sum array: 
 21
sum column arr: 
 [5 7 9]
sum row arrar: 
 [ 6 15]


In [12]:
tensor_sum = torch.sum(tensor_pt)

tensor_sum_axis_0 = torch.sum(tensor_pt, dim=0) # or axis=0

tensor_sum_axis_1 = torch.sum(tensor_pt, dim=1) # or axis=1

print(tensor_pt)
print(f'sum pytorch: \n {tensor_sum}')
print(f'sum column pytorch: \n {tensor_sum_axis_0}')
print(f'sum row pytorch: \n {tensor_sum_axis_1}')

tensor([[1, 2],
        [3, 4]])
sum pytorch: 
 10
sum column pytorch: 
 tensor([4, 6])
sum row pytorch: 
 tensor([3, 7])


In [14]:
tf_tensor_sum = tf.reduce_sum(tensor_tf)

tf_tensor_sum_axis_0 = tf.reduce_sum(tensor_tf, axis=0) 

tf_tensor_sum_axis_1 = tf.reduce_sum(tensor_tf, axis=1) 

print(tensor_pt)
print(f'sum tensorflow: \n {tf_tensor_sum}')
print(f'sum column tensorflow: \n {tf_tensor_sum_axis_0}')
print(f'sum row tensorflow: \n {tf_tensor_sum_axis_1}')

tensor([[1, 2],
        [3, 4]])
sum tensorflow: 
 10
sum column tensorflow: 
 [4 6]
sum row tensorflow: 
 [3 7]


Bài tập 2:<br>
Câu 1:

In [2]:
np.random.seed(2024)
arr_2 = np.random.randint(-10, 10, (3,4))

arr_transposed = np.transpose(arr_2)

arr_multiplicaiton = arr_2.dot(arr_transposed)

print(f'Array: \n{arr_2}')
print(f'Array after transposed: \n {arr_transposed}')
print(f'Array multiplication: \n {arr_multiplicaiton}')

Array: 
[[ -2 -10 -10  -6]
 [ -1  -9  -7   0]
 [ -8 -10  -5   7]]
Array after transposed: 
 [[ -2  -1  -8]
 [-10  -9 -10]
 [-10  -7  -5]
 [ -6   0   7]]
Array multiplication: 
 [[240 162 124]
 [162 131 133]
 [124 133 238]]


In [3]:
torch.manual_seed(2024)
tensor_pt_2 = torch.randint(-10, 10, (3,4))
print(f'Tensor pt: \n{tensor_pt_2}')

tensor_pt_transposed = torch.t(tensor_pt_2)
print(f'Tensor pt after transposed: \n {tensor_pt_transposed}')

tensor_pt_multiplicaiton = torch.matmul(tensor_pt_2, tensor_pt_transposed)
print(f'Tensor pt multiplication: \n {tensor_pt_multiplicaiton}')

Tensor pt: 
tensor([[  2,   0,  -6, -10],
        [ -7, -10,   0,   1],
        [  3,   9,   7,  -6]])
Tensor pt after transposed: 
 tensor([[  2,  -7,   3],
        [  0, -10,   9],
        [ -6,   0,   7],
        [-10,   1,  -6]])
Tensor pt multiplication: 
 tensor([[ 140,  -24,   24],
        [ -24,  150, -117],
        [  24, -117,  175]])


In [4]:
tf.random.set_seed(2024)
tensor_tf_2 = tf.experimental.numpy.random.randint(-10, 10, (3,4))
print(f'Tensor pt: \n{tensor_tf_2}')

tensor_tf_transposed = tf.transpose(tensor_tf_2)
print(f'Tensor pt after transposed: \n {tensor_tf_transposed}')

tensor_tf_multiplicaiton = tf.matmul(tensor_tf_2, tensor_tf_transposed)
print(f'Tensor pt multiplication: \n {tensor_tf_multiplicaiton}')

Tensor pt: 
[[  2   8   8  -1]
 [  3   2   2  -4]
 [-10 -10   9 -10]]
Tensor pt after transposed: 
 [[  2   3 -10]
 [  8   2 -10]
 [  8   2   9]
 [ -1  -4 -10]]
Tensor pt multiplication: 
 [[133  42 -18]
 [ 42  33   8]
 [-18   8 381]]


Cau 2:

In [5]:
np.random.seed(2024)
arr_3 = np.random.randint(-10, 10, (3, 3))
print(arr_3)

#total array
sum_arr_3 = np.sum(arr_3)
print(sum_arr_3)

#sum columns
sum_column_arr_3 = np.sum(arr_3, axis=0)
print(sum_column_arr_3)

#sum row
sum_row_arr_3 = np.sum(arr_3, axis=1)
print(sum_row_arr_3)

[[ -2 -10 -10]
 [ -6  -1  -9]
 [ -7   0  -8]]
-53
[-15 -11 -27]
[-22 -16 -15]


In [6]:
torch.manual_seed(2024)
tensor_pt_3 = torch.randint(-10, 10 ,(3, 3))
print(tensor_pt_3)

sum_tensor_pt_3 = torch.sum(tensor_pt_3)
print(sum_tensor_pt_3)

sum_column_tensor_pt_3 = torch.sum(tensor_pt_3, dim=0)
print(sum_column_tensor_pt_3)

sum_row_tensor_pt_3 = torch.sum(tensor_pt_3, dim=1)
print(sum_row_tensor_pt_3)

tensor([[  2,   0,  -6],
        [-10,  -7, -10],
        [  0,   1,   3]])
tensor(-27)
tensor([ -8,  -6, -13])
tensor([ -4, -27,   4])


In [7]:
tf.random.set_seed(2024)
tensor_tf_3 = tf.random.uniform((3, 3),-10, 10, dtype=tf.dtypes.int32)
print(tensor_tf_3)

sum_tensor_tf_3 = tf.reduce_sum(tensor_tf_3)
print(sum_tensor_tf_3)

sum_column_tensor_tf_3 = tf.reduce_sum(tensor_tf_3, axis=0)
print(sum_column_tensor_tf_3)

sum_row_tensor_tf_3 = tf.reduce_sum(tensor_tf_3, axis=1)
print(sum_row_tensor_tf_3)

tf.Tensor(
[[-6 -2  0]
 [-2  4  4]
 [-9  3  7]], shape=(3, 3), dtype=int32)
tf.Tensor(-1, shape=(), dtype=int32)
tf.Tensor([-17   5  11], shape=(3,), dtype=int32)
tf.Tensor([-8  6  1], shape=(3,), dtype=int32)
