Các hàm khởi tạo Numpy array và pytorch/tensorflow tensor - Phần 2:<br>
1. Mô tả<br>
- Tìm hiểu các hàm arrange, range, eye, random

In [2]:
import numpy as np
import torch
import tensorflow as tf

In [5]:
#a: arange, range
arr_np = np.arange(0, 5, 1)
print(arr_np)

arr_pt = torch.arange(1, 5, 1)
print(arr_pt)

arr_tf = tf.range(1, 5, 1)
print(arr_tf)

[0 1 2 3 4]
tensor([1, 2, 3, 4])
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [8]:
# hàm eye.
eye_np = np.eye(3,3)
print(eye_np)

eye_pt = torch.eye(3, 2)
print(eye_pt)

eye_tf = tf.eye(3, 3)
print(eye_tf)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
tensor([[1., 0.],
        [0., 1.],
        [0., 0.]])
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [12]:
#c, hàm random
ran_np = np.random.randint(1, 10, (2, 3))
print(ran_np)

ran_pt = torch.randint(1, 10, (2, 3))
print(ran_pt)

ran_tf = tf.random.uniform((2, 3), 1, 10, dtype=tf.int32) #dtype=tf.float kieu du lieu se la so thuc
print(ran_tf)


[[8 2 8]
 [7 6 5]]
tensor([[6, 5, 7],
        [2, 6, 4]])
tf.Tensor(
[[7 2 2]
 [4 5 8]], shape=(2, 3), dtype=int32)


2. Bai tap

In [14]:
#Cau 1: 
arr_np = np.arange(0, 10, 1) #np.arange(10)
print(arr_np)

arr_pt = torch.arange(0, 10, 1) #torch.arange(10)
print(arr_pt)

arr_tf = tf.range(0, 10, 1) #tf.range(10)
print(arr_tf)

[0 1 2 3 4 5 6 7 8 9]
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [16]:
#Cau 2:
eye_np = np.eye(3, 3)  #np.eye(3)
print(eye_np)

eye_pt = torch.eye(3,3) #torch.eye(3)
print(eye_pt)

eye_tf = tf.eye(3,3) #tf.eye(3)
print(eye_tf)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [34]:
#Cau 3:
np.random.seed(2024)
ran_np = np.random.uniform(0, 1, (3, 4)) #np.random.rand(3, 4)
print(ran_np)

torch.manual_seed(2024)
ran_pt = torch.rand(3, 4)
print(ran_pt)

tf.random.set_seed(2024)
ran_tf = tf.random.uniform((3, 4), 0, 1, dtype=tf.float32) #tf.random.uniform((3, 4))
print(ran_tf)

[[0.58801452 0.69910875 0.18815196 0.04380856]
 [0.20501895 0.10606287 0.72724014 0.67940052]
 [0.4738457  0.44829582 0.01910695 0.75259834]]
tensor([[0.5317, 0.8313, 0.9718, 0.1193],
        [0.1669, 0.3495, 0.2150, 0.6201],
        [0.4849, 0.7492, 0.1521, 0.5625]])
tf.Tensor(
[[0.90034294 0.19453335 0.36069036 0.66361904]
 [0.76605344 0.2159369  0.6261736  0.07380784]
 [0.22062695 0.934368   0.93327904 0.69267046]], shape=(3, 4), dtype=float32)


In [35]:
np.random.seed(2024)
ran_np = np.random.randint(-10, 10, (3, 4))
print(ran_np)

torch.manual_seed(2024)
ran_pt = torch.randint(-10, 10, (3, 4))
print(ran_pt)

tf.random.set_seed(2024)
ran_tf = tf.random.uniform((3, 4), -10, 10, dtype=tf.int32)
print(ran_tf)

[[ -2 -10 -10  -6]
 [ -1  -9  -7   0]
 [ -8 -10  -5   7]]
tensor([[  2,   0,  -6, -10],
        [ -7, -10,   0,   1],
        [  3,   9,   7,  -6]])
tf.Tensor(
[[-6 -2  0 -2]
 [ 4  4 -9  3]
 [ 7  1  2 -5]], shape=(3, 4), dtype=int32)
