Các Hàm khởi tạo numpy arrray và Pytorch/Tensorflow Tensor - Phần 1<br>
a. zeros<br>
b. one<br>
c. full, fill<br>

In [1]:
#import libraries
import numpy as np
import torch
import tensorflow as tf

Câu 1:

In [4]:
arr_zeros = np.zeros((3, 4))
print('Array from numpy: \n', arr_zeros)

tensor_torch_zeros = torch.zeros((3,4))
print('Tensor from Pytorch: \n', tensor_torch_zeros)

tensor_tf_zeros = tf.zeros((3,4))
print('Tensor from Pytorch: \n', tensor_tf_zeros)

Array from numpy: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Tensor from Pytorch: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Tensor from Pytorch: 
 tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


Câu 2:

In [6]:
arr_ones = np.ones((3, 4))
print('Array from numpy: \n', arr_ones)

tensor_torch_ones = torch.ones((3,4))
print('Tensor from Pytorch: \n', tensor_torch_ones)

tensor_tf_ones = tf.ones((3,4))
print('Tensor from Pytorch: \n', tensor_tf_ones)

Array from numpy: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Tensor from Pytorch: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Tensor from Pytorch: 
 tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


Câu 3:

In [7]:
arr_full = np.full((3, 4), 5)
print('Array from numpy: \n', arr_full)

tensor_torch_full = torch.full((3,4), 5)
print('Tensor from Pytorch: \n', tensor_torch_full)

tensor_tf_full = tf.fill((3,4), 5)
print('Tensor from Pytorch: \n', tensor_tf_full)

Array from numpy: 
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
Tensor from Pytorch: 
 tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])
Tensor from Pytorch: 
 tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [4]:
array_np = np.array([1,2,3])
tensor_pt = torch.tensor([4, 5, 6])
tensor_tf = tf.constant([7, 8, 9])

result = tensor_tf - (tensor_pt @ array_np) * array_np
print(tensor_tf)
print(tensor_pt @ array_np)
print(array_np)
print(result)

tf.Tensor([7 8 9], shape=(3,), dtype=int32)
tensor(32)
[1 2 3]
tf.Tensor([-25 -56 -87], shape=(3,), dtype=int32)


In [5]:
(tensor_pt @ array_np) * array_np

tensor([32, 64, 96], dtype=torch.int32)